defaults:
  - _self_
  - agent: sac
  - env: SafetyAntVelocity-v1

seed: 0
cuda: false
render: false
load_dir: null

# Global VLL Settings (Can be overridden by agent or cli)
# Note: Some agents might override these in their specific configs or code
train_vll: true
vll_steps: 2000
vll_epochs_dyn: 100
vll_epochs_cbf: 100
vll_finetune_batch_size: 5000 # Default for Tabular. Vision envs should override this.
horizon: 5
red_dim: 100

# Evaluation
eval_steps: 5000
eval_deterministic: true # Use deterministic policy (mean) for eval by default

# Output directory will be managed by Hydra (runs/date/time)
hydra:
  run:
    dir: runs_${agent.name}/${now:%Y-%m-%d_%H-%M-%S}_${agent.name}_${env_name}_H${horizon}_D${red_dim}_S${seed}
  sweep:
    dir: runs_${agent.name}/multirun/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true
