
name: all_c
gamma: 0.99
lr: 0.0003
batch_size: 256
hidden_size: 256
num_steps: 1000000
replay_size: 200000
start_steps: 10000
tau: 0.005
alpha: 0.2
automatic_entropy_tuning: false
updates_per_step: 1
target_update_interval: 1
policy: Gaussian

# VLL Finetuning Defaults for SAC Teacher
vll_finetune_steps: 50000
vll_finetune_epochs_dyn: 20
vll_finetune_epochs_cbf: 20

train_vll: false

# ALL-C Specific
initial_epochs: 200          # Epochs for first VDK training at start_steps
on_policy_batch_size: 2048   # Buffer size before periodic update
