# @package _global_
name: ppo
gamma: 0.99
lr: 0.0003
batch_size: 2048
mini_batch_size: 256
hidden_size: 256
num_steps: 200000
replay_size: 1000000
start_steps: 0

# VLL Finetuning Defaults for PPO
vll_finetune_steps: 20000
vll_finetune_epochs_dyn: 50
vll_finetune_epochs_cbf: 50
